### PR TITLE
Update dashboard.txt

### PR DESCRIPTION
**Pull request by qxzzxq**
A small doubt on the translation of **Due in** in line 19, maybe it's better to say "距离下次运行"

### CODE REVIEW

**Comment by spencerjunraid** [comment]
Thank you for the suggestion. What do you think @typing-more?

**Comment by spencerjunraid** [comment]
Hello, there are a number of PR's open on various files and I will implement them all manually due to some suggestions being accepted, others not. See here: https://drive.google.com/file/d/1Pb8nymWhFsdnURi-meF9mrBtUuRP7I66/view?usp=sharing

**Comment by spencerjunraid** [comment]
I would like to add you as a contributor to the Chinese language pack. Could you please confirm the name you would like to appear?

**Comment by qxzzxq** [comment]
@spencerjunraid thank you :) my name is `Xuzhou Qin`

**Comment by spencerjunraid** [comment]
Screen Shot 2021-01-19 at 9 52 26 AM

Great, thank you Xuzhou Qin for the additions to the language pack :-)

**Pull request closed without merging**
