### PR TITLE
Update translation for Unassigned Devices

### PR DESCRIPTION
**Pull request by bianyukun1213**

### CODE REVIEW

**Comment by bianyukun1213** [comment]
I deleted and merged some files to follow the English version’s directory structure. But now the UD section in the Main page only displays in English. Do I need to do something to fix it? 

image

**Comment by bianyukun1213** [comment]
How should I deal with [this line](https://github.com/bianyukun1213/lang-zh_CN/blob/master/Unassigned%20Devices/unassigneddevicessettings.txt#L133)? Keep the `_(disable it in Windows)_` untouched, or translate that part to Chinese and **keep** the `_(` and `)_`, or translate but **remove** the `_(` and `)_`?

**Comment by spencerjunraid** [comment]
> How should I deal with [this line](https://github.com/bianyukun1213/lang-zh_CN/blob/master/Unassigned%20Devices/unassigneddevicessettings.txt#L133)? Keep the `_(disable it in Windows)_` untouched, or translate that part to Chinese and **keep** the `_(` and `)_`, or translate but **remove** the `_(` and `)_`?

Hello, I believe you leave that in English.

**Comment by spencerjunraid** [comment]
Thank you!

**Pull request merged**
