### PR TITLE
update translations.txt

### PR DESCRIPTION
**Pull request by hyird**
#57

### CODE REVIEW

**Comment by jinnyu** [comment]
Hi, I have noticed your modification(2d6783c9d7ab613003276d8a900444c9a7f5add7), 
but what I want to express is that "Load" has different meanings in different contexts. 
The word "Load" in English is all "Load", 
but it has a different meaning in Chinese, 
so the overall situation is straightforward. 
It is inappropriate to change "加载" to "负载", 
that’s why I proposed to use a separate field on the DashBoard page to represent "Load".

**Comment by hyird** [comment]
image
完全不慌  带有 load的就5个 单独的load就这一个  改了这个并不会影响其他的显示，你多虑了

**Comment by spencerjunraid** [comment]
Will keep as is. Load here is like 'Now Loading'.

**Comment by hyird** [comment]
> as is. Load here is like 'Now Loading'.
how about not translating it？

**Comment by hyird** [comment]
> Will keep as is. Load here is like 'Now Loading'.

how about not translating it?

**Comment by spencerjunraid** [comment]
Can do that if that makes more sense. Do you think leaving in English "load" is better?

**Comment by hyird** [comment]
> at makes more sense. Do you think leaving in English "load" is better?

 I just  would rather not translate than see mistakes
to show cpu usage，use “加载” ,i think it‘s wrong,

**Comment by spencerjunraid** [comment]
Ok- can you do a PR so I am not changing myself?

**Pull request closed without merging**
