### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by KevinLADLee**
Update dashboard.txt, docker.txt, javascript.txt, main.txt, plugin.txt translation file.

Add some translations.

Change some terms that do not need to be translated.

### CODE REVIEW

**Comment by spencerjunraid** [comment]
Hello @KevinLADLee - many of these files have already been completed. Please see Asana: https://app.asana.com/0/1180650261968138/board

Let me know if you have any questions about this.

**Comment by KevinLADLee** [comment]
> Hello @KevinLADLee - many of these files have already been completed. Please see Asana: https://app.asana.com/0/1180650261968138/board
> 
> Let me know if you have any questions about this.

It looks like I don't have access to this board...

**Comment by spencerjunraid** [comment]
Did you originally talk to me before we began translating? Could you email me @spencerj@unraid.net please?

**Comment by KevinLADLee** [comment]
> Did you originally talk to me before we began translating? Could you email me @ [spencerj@unraid.net](mailto:spencerj@unraid.net) please?

ok.

**Pull request closed without merging**
